name: WynboxTrade
version: '1.0-SNAPSHOT'
main: fr.wynbox.trade.WynboxTrade
api-version: '1.20'
authors: [TikOf]
description: Plugin de trade pour Minecraft
softdepend: [Vault]

commands:
  trade:
    description: Commande principale pour échanger avec un joueur
    usage: |
      §e/trade <joueur> §7- Envoyer une demande d'échange
      §e/trade accept [joueur] §7- Accepter une demande d'échange
      §e/trade deny [joueur] §7- Refuser une demande d'échange
    aliases: [t]

permissions:
  wynbox.trade:
    description: Permission pour utiliser la commande /trade
    default: true
  wynbox.trade.money:
    description: Permission pour utiliser la fonction d'argent dans les trades
    default: true
  wynbox.trade.bypass.distance:
    description: Permission pour ignorer la distance maximale de trade
    default: op
  wynbox.trade.admin:
    description: Permission pour toutes les commandes administratives
    default: op
    children:
      wynbox.trade: true
      wynbox.trade.money: true
      wynbox.trade.bypass.distance: true
